# Generated by Django 3.2 on 2021-04-28 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('NAME', models.CharField(blank=True, max_length=200, null=True)),
                ('BRAND', models.CharField(blank=True, max_length=200, null=True)),
                ('CATEGORY', models.CharField(blank=True, max_length=200, null=True)),
                ('DESCRIPTION', models.TextField(blank=True, null=True)),
                ('RATING', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('NUM_REVIEWS', models.IntegerField(blank=True, default=0, null=True)),
                ('PRICE', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('COUNT_IN_STOCK', models.IntegerField(blank=True, default=0, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True)),
                ('ID', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('USER', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
