# Generated by Django 3.2 on 2021-04-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rewiew'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ID',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='BRAND',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='CATEGORY',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='COUNT_IN_STOCK',
            new_name='countInStock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='CREATED_AT',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='DESCRIPTION',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='NAME',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='NUM_REVIEWS',
            new_name='numReviews',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='PRICE',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='RATING',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='USER',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rewiew',
            old_name='ID',
            new_name='_id',
        ),
        migrations.RenameField(
            model_name='rewiew',
            old_name='COMMENT',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='rewiew',
            old_name='NAME',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='rewiew',
            old_name='PRODUCT',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='rewiew',
            old_name='RATING',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='rewiew',
            old_name='USER',
            new_name='user',
        ),
    ]
