# Generated by Django 3.2 on 2021-04-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='IMAGE',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
